In [1]:
# elements acessings row/colomn
# loc and iloc.....>location and index location based

In [5]:
import pandas as pd
df=pd.DataFrame({"name":['siri','kalpu','saru','prem'],
                "rollnumber":[495,554,461,496],
                "branch":["ece","cse","eee","civil"]},index=[1,2,3,4])

In [6]:
df

name  rollnumber branch
1   siri         495    ece
2  kalpu         554    cse
3   saru         461    eee
4   prem         496  civil

In [7]:
df.loc[2]

name          kalpu
rollnumber      554
branch          cse
Name: 2, dtype: object

In [8]:
df.loc[4]

name           prem
rollnumber      496
branch        civil
Name: 4, dtype: object

In [9]:
df.loc[3]['rollnumber']

461

In [10]:
df.iloc[0]

name          siri
rollnumber     495
branch         ece
Name: 1, dtype: object

In [11]:
df.iloc[3]

name           prem
rollnumber      496
branch        civil
Name: 4, dtype: object

In [12]:
df.iloc[2]["branch"]

'eee'

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4 entries, 1 to 4
Data columns (total 3 columns):
name          4 non-null object
rollnumber    4 non-null int64
branch        4 non-null object
dtypes: int64(1), object(2)
memory usage: 288.0+ bytes


In [14]:
df.describe()

rollnumber
count      4.0000
mean     501.5000
std       38.5962
min      461.0000
25%      486.5000
50%      495.5000
75%      510.5000
max      554.0000

In [15]:
df.count()

name          4
rollnumber    4
branch        4
dtype: int64

In [16]:
df.dtypes

name          object
rollnumber     int64
branch        object
dtype: object

In [17]:
df.count(axis=0)#colounm count

name          4
rollnumber    4
branch        4
dtype: int64

In [18]:
df.count(axis=1)#rows count

1    3
2    3
3    3
4    3
dtype: int64

In [19]:
df

name  rollnumber branch
1   siri         495    ece
2  kalpu         554    cse
3   saru         461    eee
4   prem         496  civil

In [20]:
df.set_index(["rollnumber"])

name branch
rollnumber              
495          siri    ece
554         kalpu    cse
461          saru    eee
496          prem  civil

In [21]:
df.set_index(["branch"])

name  rollnumber
branch                   
ece      siri         495
cse     kalpu         554
eee      saru         461
civil    prem         496

In [22]:
df.set_index(["name"])

rollnumber branch
name                    
siri          495    ece
kalpu         554    cse
saru          461    eee
prem          496  civil

In [23]:
df.set_index(["rollnumber","branch"])

name
rollnumber branch       
495        ece      siri
554        cse     kalpu
461        eee      saru
496        civil    prem

In [24]:

frame=pd.Series([9,3,5,6,21,"none"])


In [25]:
frame

0       9
1       3
2       5
3       6
4      21
5    none
dtype: object

In [26]:
frame.describe()

count     6
unique    6
top       6
freq      1
dtype: int64

In [28]:
frame.count()

6

In [31]:
import numpy as np

In [38]:
x=np.arange(10)

In [39]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
x.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [50]:
data=pd.DataFrame(np.arange(12).reshape(4,3),columns=['a','b','c'])


In [51]:
data

a   b   c
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11

In [52]:
y=np.arange(20)

In [53]:
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [54]:
y.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [69]:
data1=pd.DataFrame(np.arange(20).reshape(5,4),columns=['a','b','c','d'])

In [70]:
data1

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [71]:
data1.loc[1,'b']=np.nan

In [72]:
data1

a     b   c   d
0   0   1.0   2   3
1   4   NaN   6   7
2   8   9.0  10  11
3  12  13.0  14  15
4  16  17.0  18  19

In [73]:
data1.isnull().sum()

a    0
b    1
c    0
d    0
dtype: int64

In [74]:
dd=data+data1
dd

a     b   c   d
0   0   2.0   4   6
1   8   NaN  12  14
2  16  18.0  20  22
3  24  26.0  28  30
4  32  34.0  36  38

In [75]:
dd=df.add(data)
dd

a   b branch   c   d name  rollnumber
0 NaN NaN    NaN NaN NaN  NaN         NaN
1 NaN NaN    NaN NaN NaN  NaN         NaN
2 NaN NaN    NaN NaN NaN  NaN         NaN
3 NaN NaN    NaN NaN NaN  NaN         NaN
4 NaN NaN    NaN NaN NaN  NaN         NaN

In [76]:
dd.add(data,fill_value=9)

a     b branch     c     d name  rollnumber
0   9.0  10.0    NaN  11.0  12.0  NaN         NaN
1  13.0   NaN    NaN  15.0  16.0  NaN         NaN
2  17.0  18.0    NaN  19.0  20.0  NaN         NaN
3  21.0  22.0    NaN  23.0  24.0  NaN         NaN
4  25.0  26.0    NaN  27.0  28.0  NaN         NaN

In [78]:
dd.add(data,fill_value=6)

a     b branch     c     d name  rollnumber
0   6.0   7.0    NaN   8.0   9.0  NaN         NaN
1  10.0   NaN    NaN  12.0  13.0  NaN         NaN
2  14.0  15.0    NaN  16.0  17.0  NaN         NaN
3  18.0  19.0    NaN  20.0  21.0  NaN         NaN
4  22.0  23.0    NaN  24.0  25.0  NaN         NaN

In [80]:
np.random.randn(2,4)

array([[ 0.63045595,  0.10874754, -0.61113268, -1.11907786],
       [-0.86658709, -1.14957479, -1.23251965,  1.54920574]])

In [85]:
np.random.rand(2,11)

array([[0.96037458, 0.21271133, 0.23759283, 0.66324346, 0.65396328,
        0.69551971, 0.99620269, 0.37337789, 0.52188877, 0.42400199,
        0.62255707],
       [0.01162782, 0.2287779 , 0.31654542, 0.16737782, 0.12423528,
        0.0424164 , 0.66688231, 0.83577813, 0.80191348, 0.4781194 ,
        0.63874834]])

In [87]:
#Creating dataframe with random values
s=pd.DataFrame(np.random.randn(3,4))
s

0         1         2         3
0 -0.923150 -0.441145 -0.214393  0.008451
1 -0.651649  1.350911  0.320276  0.418214
2 -0.610141  1.405954 -1.690934 -0.303372

In [88]:
s=pd.DataFrame(np.random.randn(3,4),index=['c','b','a'],columns=['s1','s2','s3','s4'])
s

s1        s2        s3        s4
c -0.204915 -0.340896 -0.113982 -1.278355
b  0.150639  0.427949 -0.689949 -0.909516
a -0.141239 -1.018895 -0.594264 -0.577297

In [89]:
s.index=['c','b','a']

In [90]:
s

s1        s2        s3        s4
c -0.204915 -0.340896 -0.113982 -1.278355
b  0.150639  0.427949 -0.689949 -0.909516
a -0.141239 -1.018895 -0.594264 -0.577297

In [91]:
#reindexing
s1=s.reindex(['a','b','c','d'])
s1

s1        s2        s3        s4
a -0.141239 -1.018895 -0.594264 -0.577297
b  0.150639  0.427949 -0.689949 -0.909516
c -0.204915 -0.340896 -0.113982 -1.278355
d       NaN       NaN       NaN       NaN

In [92]:
s1.isnull()

s1     s2     s3     s4
a  False  False  False  False
b  False  False  False  False
c  False  False  False  False
d   True   True   True   True

In [93]:
s1.isnull().sum()

s1    1
s2    1
s3    1
s4    1
dtype: int64

In [94]:
s1.dropna() #dropping the null values

s1        s2        s3        s4
a -0.141239 -1.018895 -0.594264 -0.577297
b  0.150639  0.427949 -0.689949 -0.909516
c -0.204915 -0.340896 -0.113982 -1.278355

In [96]:
s1.fillna(3) #filling a null values

s1        s2        s3        s4
a -0.141239 -1.018895 -0.594264 -0.577297
b  0.150639  0.427949 -0.689949 -0.909516
c -0.204915 -0.340896 -0.113982 -1.278355
d  3.000000  3.000000  3.000000  3.000000

In [97]:
s1.fillna(method='bfill',axis=1).fillna(1)#backward filling

s1        s2        s3        s4
a -0.141239 -1.018895 -0.594264 -0.577297
b  0.150639  0.427949 -0.689949 -0.909516
c -0.204915 -0.340896 -0.113982 -1.278355
d  1.000000  1.000000  1.000000  1.000000

In [98]:
s1.fillna(method='ffill',axis=0).fillna(1)#forward filling

s1        s2        s3        s4
a -0.141239 -1.018895 -0.594264 -0.577297
b  0.150639  0.427949 -0.689949 -0.909516
c -0.204915 -0.340896 -0.113982 -1.278355
d -0.204915 -0.340896 -0.113982 -1.278355

In [99]:
s1.isnull()

s1     s2     s3     s4
a  False  False  False  False
b  False  False  False  False
c  False  False  False  False
d   True   True   True   True

In [100]:
s1.isna()

s1     s2     s3     s4
a  False  False  False  False
b  False  False  False  False
c  False  False  False  False
d   True   True   True   True

In [102]:
pd.isna(s1['s4'])

a    False
b    False
c    False
d     True
Name: s4, dtype: bool

In [103]:
# data replacing
s1

s1        s2        s3        s4
a -0.141239 -1.018895 -0.594264 -0.577297
b  0.150639  0.427949 -0.689949 -0.909516
c -0.204915 -0.340896 -0.113982 -1.278355
d       NaN       NaN       NaN       NaN

In [104]:
s1.replace(0.237804,9999)

s1        s2        s3        s4
a -0.141239 -1.018895 -0.594264 -0.577297
b  0.150639  0.427949 -0.689949 -0.909516
c -0.204915 -0.340896 -0.113982 -1.278355
d       NaN       NaN       NaN       NaN

In [107]:
df33.replace(4,9999)

NameError: name 'df33' is not defined

In [111]:
##index sorting and ranking
s2=s1.reindex(['a','c','b','e'])
s2
#s1

s1        s2        s3        s4
a -0.141239 -1.018895 -0.594264 -0.577297
c -0.204915 -0.340896 -0.113982 -1.278355
b  0.150639  0.427949 -0.689949 -0.909516
e       NaN       NaN       NaN       NaN

In [112]:
s2.sort_index()

s1        s2        s3        s4
a -0.141239 -1.018895 -0.594264 -0.577297
b  0.150639  0.427949 -0.689949 -0.909516
c -0.204915 -0.340896 -0.113982 -1.278355
e       NaN       NaN       NaN       NaN

In [113]:
s3=s1.columns=['s4','s2','s1','s5']


In [114]:
s3

['s4', 's2', 's1', 's5']

In [115]:
s1.sort_index(axis=1)

s1        s2        s4        s5
a -0.594264 -1.018895 -0.141239 -0.577297
b -0.689949  0.427949  0.150639 -0.909516
c -0.113982 -0.340896 -0.204915 -1.278355
d       NaN       NaN       NaN       NaN

In [116]:
s1.sort_index(axis=0)

s4        s2        s1        s5
a -0.141239 -1.018895 -0.594264 -0.577297
b  0.150639  0.427949 -0.689949 -0.909516
c -0.204915 -0.340896 -0.113982 -1.278355
d       NaN       NaN       NaN       NaN

In [124]:
#groupby
animal_df=pd.DataFrame({'name':['dog','cat','cow','dog','cat'],'place':['zoo','ooo','zoo','oo','zoo'],'feature':['q','s','s','p','s']})                                                                                                         

In [125]:
animal_df

name place feature
0  dog   zoo       q
1  cat   ooo       s
2  cow   zoo       s
3  dog    oo       p
4  cat   zoo       s

In [126]:
animal_df.groupby('name').count()

place  feature
name                
cat       2        2
cow       1        1
dog       2        2

In [127]:
animal_df.groupby('place').count()

name  feature
place               
oo        1        1
ooo       1        1
zoo       3        3

In [128]:
animal_df.groupby(['name','feature']).sum()

place
name feature        
cat  s        ooozoo
cow  s           zoo
dog  p            oo
     q           zoo

In [129]:
#Ranking
animal_df=pd.DataFrame({'name':['dog','cat','cow','dog','cat'],'place':['zoo','ooo','zoo','oo','zoo'],'no-legs':[4,2,3,2,np.nan]})                                                                                  

In [131]:
animal_df

name place  no-legs
0  dog   zoo      4.0
1  cat   ooo      2.0
2  cow   zoo      3.0
3  dog    oo      2.0
4  cat   zoo      NaN

In [133]:
animal_df["rank1"]=animal_df['no-legs'].rank()
animal_df

name place  no-legs  rank1
0  dog   zoo      4.0    4.0
1  cat   ooo      2.0    1.5
2  cow   zoo      3.0    3.0
3  dog    oo      2.0    1.5
4  cat   zoo      NaN    NaN

In [134]:
animal_df["max-rank"]=animal_df['no-legs'].rank(method="max")
animal_df

name place  no-legs  rank1  max-rank
0  dog   zoo      4.0    4.0       4.0
1  cat   ooo      2.0    1.5       2.0
2  cow   zoo      3.0    3.0       3.0
3  dog    oo      2.0    1.5       2.0
4  cat   zoo      NaN    NaN       NaN

In [138]:
animal_df["first-rank"]=animal_df['no-legs'].rank(method="first")

In [136]:
animal_df

name place  no-legs  rank1  max-rank  first-rank
0  dog   zoo      4.0    4.0       4.0         4.0
1  cat   ooo      2.0    1.5       2.0         1.5
2  cow   zoo      3.0    3.0       3.0         3.0
3  dog    oo      2.0    1.5       2.0         1.5
4  cat   zoo      NaN    NaN       NaN         5.0

In [139]:
animal_df["non-rank"]=animal_df['no-legs'].rank(na_option="bottom")
animal_df

name place  no-legs  rank1  max-rank  first-rank  non-rank
0  dog   zoo      4.0    4.0       4.0         4.0       4.0
1  cat   ooo      2.0    1.5       2.0         1.0       1.5
2  cow   zoo      3.0    3.0       3.0         3.0       3.0
3  dog    oo      2.0    1.5       2.0         2.0       1.5
4  cat   zoo      NaN    NaN       NaN         NaN       5.0

In [142]:
animal_df["pct-rank"]=animal_df['no-legs'].rank(pct="True")

In [143]:
animal_df

name place  no-legs  rank1  max-rank  first-rank  non-rank  pct-rank
0  dog   zoo      4.0    4.0       4.0         4.0       4.0     1.000
1  cat   ooo      2.0    1.5       2.0         1.0       1.5     0.375
2  cow   zoo      3.0    3.0       3.0         3.0       3.0     0.750
3  dog    oo      2.0    1.5       2.0         2.0       1.5     0.375
4  cat   zoo      NaN    NaN       NaN         NaN       5.0       NaN

In [144]:
#categorise
data_frame=pd.DataFrame({'x':[1,2,3,4,5],'y':[6,7,8,9,10]})
data_frame

x   y
0  1   6
1  2   7
2  3   8
3  4   9
4  5  10

In [146]:
data_frame["cc"]=data_frame['y'].astype('category')

In [147]:
data_frame

x   y  cc
0  1   6   6
1  2   7   7
2  3   8   8
3  4   9   9
4  5  10  10

In [148]:
data_frame["cc"]

0     6
1     7
2     8
3     9
4    10
Name: cc, dtype: category
Categories (5, int64): [6, 7, 8, 9, 10]

In [150]:
data_frame["cc"].cat.categories=["good","bad","worst","verybad","verygood"]
data_frame

x   y        cc
0  1   6      good
1  2   7       bad
2  3   8     worst
3  4   9   verybad
4  5  10  verygood

In [151]:
data_frame["cc"]=data_frame["cc"].cat.set_categories(["good","bad","worst","verybad","verygood"])
data_frame

x   y        cc
0  1   6      good
1  2   7       bad
2  3   8     worst
3  4   9   verybad
4  5  10  verygood

In [152]:
data_frame.sort_values('cc')

x   y        cc
0  1   6      good
1  2   7       bad
2  3   8     worst
3  4   9   verybad
4  5  10  verygood

In [153]:
data_frame.groupby("cc").sum()

x   y
cc             
good      1   6
bad       2   7
worst     3   8
verybad   4   9
verygood  5  10

In [2]:
#Reading data
import pandas as pd
df=pd.read_table("sample.csv")
df

C:\Users\public\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  This is separate from the ipykernel package so we can avoid doing imports until


234
0    6534
1  764378

In [3]:
df.tail(1)

234
1  764378

In [5]:
df=pd.read_table("ex1.csv",sep=',')
df

C:\Users\public\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead.
  """Entry point for launching an IPython kernel.


a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo